Un ejemplo para Rmarkdown, con graficos
wfjvdham/Rcourse pull request #1
Opened 2017-10-29 16:46 UTC by Christianivh

Este es un gráfico con markdown

2017-10-29 17:06 UTC, wfjvdham commented
Con solo el archivo de .md yo no puedo cambiar or mostrar el codigo R. Es posible tambien subir el archivo .Rmd?

2017-10-30 22:42 UTC, Christianivh commented
Hola Wim, porfa cuando puedas revisas mis cambios.
Slds,
Christian

2017-10-31 13:22 UTC, wfjvdham requested changes
Después ceda transforma tu puedes mostrar en un table pequeño (solo los primero 5 filas por ejemplo) el resultado. En este manera es mas fácil entender que paso en el función.

2017-10-31 13:22 UTC, wfjvdham commented on student_examples/tidy_clase.Rmd
> +---
En este parte hay tabs y espacios. Cuando yo quiero correr yo tengo un error con eso. Tu puedes cambiar a solo dos espacios por un tab.

2017-10-31 13:22 UTC, wfjvdham commented on student_examples/tidy_clase.Rmd
> +  geom_tile(aes(fill = TMAX), colour = "white") +
`month` es un variable discreta y no continua.

2017-10-31 13:22 UTC, wfjvdham commented on student_examples/tidy_clase.Rmd
> +  geom_tile(aes(fill = TMAX), colour = "white") +
`day` es un character en tu data frame y por eso el orden es raro. Cuando tu vas a cambiar a un numero es mejor

2017-12-09 19:45 UTC, closed without merging